#!/usr/bin/env bash

# Set up Arrow library path
export LD_LIBRARY_PATH="/nix/store/bi90gd0fbr5icl03scxylsdv4ba9sc8d-arrow-cpp-20.0.0/lib:$LD_LIBRARY_PATH"

# FlowCtl Configuration (optional)
export ENABLE_FLOWCTL=${ENABLE_FLOWCTL:-false}
export FLOWCTL_ENDPOINT=${FLOWCTL_ENDPOINT:-localhost:8080}
export FLOWCTL_HEARTBEAT_INTERVAL=${FLOWCTL_HEARTBEAT_INTERVAL:-10s}

# Component-specific FlowCtl overrides (optional)
export TTP_ARROW_PROCESSOR_ENABLE_FLOWCTL=${TTP_ARROW_PROCESSOR_ENABLE_FLOWCTL:-}
export TTP_ARROW_PROCESSOR_FLOWCTL_ENDPOINT=${TTP_ARROW_PROCESSOR_FLOWCTL_ENDPOINT:-}
export TTP_ARROW_PROCESSOR_FLOWCTL_HEARTBEAT_INTERVAL=${TTP_ARROW_PROCESSOR_FLOWCTL_HEARTBEAT_INTERVAL:-}

# Advanced FlowCtl Features (Phase 4)
export CONNECTION_POOL_MAX_CONNECTIONS=${CONNECTION_POOL_MAX_CONNECTIONS:-10}
export CONNECTION_POOL_MIN_CONNECTIONS=${CONNECTION_POOL_MIN_CONNECTIONS:-2}
export CONNECTION_POOL_IDLE_TIMEOUT=${CONNECTION_POOL_IDLE_TIMEOUT:-5m}
export MONITORING_INTERVAL=${MONITORING_INTERVAL:-5s}

# Component-specific configuration
export TTP_ARROW_PROCESSOR_PORT=${TTP_ARROW_PROCESSOR_PORT:-8816}
export TTP_ARROW_PROCESSOR_HEALTH_PORT=${TTP_ARROW_PROCESSOR_HEALTH_PORT:-8088}
export TTP_ARROW_PROCESSOR_SOURCE_ENDPOINT=${TTP_ARROW_PROCESSOR_SOURCE_ENDPOINT:-localhost:8815}
export TTP_ARROW_PROCESSOR_THREADS=${TTP_ARROW_PROCESSOR_THREADS:-4}
export TTP_ARROW_PROCESSOR_LOG_LEVEL=${TTP_ARROW_PROCESSOR_LOG_LEVEL:-info}

echo "Starting ttp-arrow-processor..."
echo "Arrow Flight server: localhost:${TTP_ARROW_PROCESSOR_PORT}"
echo "Health endpoint: http://localhost:${TTP_ARROW_PROCESSOR_HEALTH_PORT}/health"
echo "Source endpoint: ${TTP_ARROW_PROCESSOR_SOURCE_ENDPOINT}"
echo "Processing threads: ${TTP_ARROW_PROCESSOR_THREADS}"
echo "FlowCtl Integration: $ENABLE_FLOWCTL"
if [ "$ENABLE_FLOWCTL" = "true" ]; then
    echo "FlowCtl Endpoint: $FLOWCTL_ENDPOINT"
    echo "Heartbeat Interval: $FLOWCTL_HEARTBEAT_INTERVAL"
    echo "Connection Pool: ${CONNECTION_POOL_MIN_CONNECTIONS}-${CONNECTION_POOL_MAX_CONNECTIONS} connections"
fi
echo ""

# Run the component
exec ./ttp-arrow-processor