// Code generated by go generate ./pkg/bronze/columnar; DO NOT EDIT.

package columnar

import (
	"fmt"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/apache/arrow-go/v18/arrow/memory"
	"github.com/withObsrvr/obsrvr-stellar-components/pkg/contracts"
	extract "github.com/withObsrvr/stellar-extract"
)

var transactionsBuilderLayout = mustTypedLayout("transactions_row_v2")

type TransactionsBuilder struct{ *extractRecordBuilder }

func NewTransactionsBuilder(allocator memory.Allocator, reserve int) *TransactionsBuilder {
	return &TransactionsBuilder{extractRecordBuilder: newExtractRecordBuilder(transactionsBuilderLayout.Schema, allocator, reserve)}
}

func (builder *TransactionsBuilder) Schema() *arrow.Schema { return transactionsBuilderLayout.Schema }

func (builder *TransactionsBuilder) Append(row extract.TransactionData, rawOverrides map[string]any) error {
	if builder == nil || builder.record == nil {
		return fmt.Errorf("typed extract builder is closed")
	}
	fields := builder.record.Fields()
	fields[0].(*array.Int64Builder).Append(int64(row.LedgerSequence))
	fields[1].(*array.StringBuilder).Append(row.TransactionHash)
	fields[2].(*array.StringBuilder).Append(row.SourceAccount)
	fields[3].(*array.Int64Builder).Append(int64(row.FeeCharged))
	fields[4].(*array.Int64Builder).Append(int64(row.MaxFee))
	fields[5].(*array.BooleanBuilder).Append(row.Successful)
	fields[6].(*array.StringBuilder).Append(row.TransactionResultCode)
	if err := appendIntAsInt32(fields[7].(*array.Int32Builder), row.OperationCount); err != nil {
		return fmt.Errorf("operation_count: %w", err)
	}
	appendOptionalString(fields[8].(*array.StringBuilder), row.MemoType)
	appendOptionalString(fields[9].(*array.StringBuilder), row.Memo)
	fields[10].(*array.TimestampBuilder).Append(arrow.Timestamp(row.CreatedAt.UnixMicro()))
	fields[11].(*array.Int64Builder).Append(int64(row.AccountSequence))
	fields[12].(*array.Int64Builder).Append(int64(row.LedgerRange))
	appendOptionalString(fields[13].(*array.StringBuilder), row.SourceAccountMuxed)
	fields[14].AppendNull()
	fields[15].AppendNull()
	fields[16].AppendNull()
	fields[17].AppendNull()
	fields[18].AppendNull()
	appendOptionalInt64(fields[19].(*array.Int64Builder), row.TimeboundsMinTime)
	appendOptionalInt64(fields[20].(*array.Int64Builder), row.TimeboundsMaxTime)
	fields[21].AppendNull()
	fields[22].AppendNull()
	fields[23].AppendNull()
	fields[24].AppendNull()
	appendOptionalInt64(fields[25].(*array.Int64Builder), row.SorobanResourcesInstructions)
	appendOptionalInt64(fields[26].(*array.Int64Builder), row.SorobanResourcesReadBytes)
	appendOptionalInt64(fields[27].(*array.Int64Builder), row.SorobanResourcesWriteBytes)
	fields[28].AppendNull()
	fields[29].AppendNull()
	fields[30].AppendNull()
	fields[31].AppendNull()
	fields[32].AppendNull()
	fields[33].AppendNull()
	fields[34].AppendNull()
	appendOptionalString(fields[35].(*array.StringBuilder), row.SorobanHostFunctionType)
	appendOptionalString(fields[36].(*array.StringBuilder), row.SorobanContractID)
	fields[37].AppendNull()
	if err := appendIntAsInt32(fields[38].(*array.Int32Builder), row.SignaturesCount); err != nil {
		return fmt.Errorf("signatures_count: %w", err)
	}
	fields[39].(*array.BooleanBuilder).Append(row.NewAccount)
	appendOptionalInt64(fields[40].(*array.Int64Builder), row.RentFeeCharged)
	if err := appendRawTransactionString(fields[41].(*array.StringBuilder), rawOverrides, "tx_envelope"); err != nil {
		return fmt.Errorf("tx_envelope: %w", err)
	}
	if err := appendRawTransactionString(fields[42].(*array.StringBuilder), rawOverrides, "tx_result"); err != nil {
		return fmt.Errorf("tx_result: %w", err)
	}
	if err := appendRawTransactionString(fields[43].(*array.StringBuilder), rawOverrides, "tx_meta"); err != nil {
		return fmt.Errorf("tx_meta: %w", err)
	}
	fields[44].AppendNull()
	fields[45].AppendNull()
	fields[46].AppendNull()
	appendOptionalString(fields[47].(*array.StringBuilder), row.EraID)
	fields[48].(*array.StringBuilder).Append(contracts.ExtractionVersion)
	fields[49].(*array.Int64Builder).Append(int64(row.TransactionID))
	return nil
}

var operationsBuilderLayout = mustTypedLayout("operations_row_v2")

type OperationsBuilder struct{ *extractRecordBuilder }

func NewOperationsBuilder(allocator memory.Allocator, reserve int) *OperationsBuilder {
	return &OperationsBuilder{extractRecordBuilder: newExtractRecordBuilder(operationsBuilderLayout.Schema, allocator, reserve)}
}

func (builder *OperationsBuilder) Schema() *arrow.Schema { return operationsBuilderLayout.Schema }

func (builder *OperationsBuilder) Append(row extract.OperationData) error {
	if builder == nil || builder.record == nil {
		return fmt.Errorf("typed extract builder is closed")
	}
	fields := builder.record.Fields()
	fields[0].(*array.StringBuilder).Append(row.TransactionHash)
	if err := appendIntAsInt32(fields[1].(*array.Int32Builder), row.OperationIndex); err != nil {
		return fmt.Errorf("operation_index: %w", err)
	}
	fields[2].(*array.Int64Builder).Append(int64(row.LedgerSequence))
	fields[3].(*array.StringBuilder).Append(row.SourceAccount)
	if err := appendIntAsInt32(fields[4].(*array.Int32Builder), row.OpType); err != nil {
		return fmt.Errorf("type: %w", err)
	}
	fields[5].(*array.StringBuilder).Append(row.TypeString)
	fields[6].(*array.TimestampBuilder).Append(arrow.Timestamp(row.CreatedAt.UnixMicro()))
	fields[7].(*array.BooleanBuilder).Append(row.TransactionSuccessful)
	appendOptionalString(fields[8].(*array.StringBuilder), row.OperationResultCode)
	fields[9].AppendNull()
	fields[10].(*array.Int64Builder).Append(int64(row.LedgerRange))
	appendOptionalString(fields[11].(*array.StringBuilder), row.SourceAccountMuxed)
	appendOptionalString(fields[12].(*array.StringBuilder), row.Asset)
	appendOptionalString(fields[13].(*array.StringBuilder), row.AssetType)
	appendOptionalString(fields[14].(*array.StringBuilder), row.AssetCode)
	appendOptionalString(fields[15].(*array.StringBuilder), row.AssetIssuer)
	appendOptionalString(fields[16].(*array.StringBuilder), row.SourceAsset)
	appendOptionalString(fields[17].(*array.StringBuilder), row.SourceAssetType)
	appendOptionalString(fields[18].(*array.StringBuilder), row.SourceAssetCode)
	appendOptionalString(fields[19].(*array.StringBuilder), row.SourceAssetIssuer)
	appendOptionalInt64(fields[20].(*array.Int64Builder), row.Amount)
	appendOptionalInt64(fields[21].(*array.Int64Builder), row.SourceAmount)
	appendOptionalInt64(fields[22].(*array.Int64Builder), row.DestinationMin)
	appendOptionalInt64(fields[23].(*array.Int64Builder), row.StartingBalance)
	appendOptionalString(fields[24].(*array.StringBuilder), row.Destination)
	appendOptionalInt64(fields[25].(*array.Int64Builder), row.TrustlineLimit)
	fields[26].AppendNull()
	fields[27].AppendNull()
	fields[28].AppendNull()
	fields[29].AppendNull()
	appendOptionalString(fields[30].(*array.StringBuilder), row.BalanceID)
	fields[31].AppendNull()
	appendOptionalString(fields[32].(*array.StringBuilder), row.SponsoredID)
	appendOptionalInt64(fields[33].(*array.Int64Builder), row.OfferID)
	appendOptionalString(fields[34].(*array.StringBuilder), row.Price)
	appendOptionalString(fields[35].(*array.StringBuilder), row.PriceR)
	appendOptionalString(fields[36].(*array.StringBuilder), row.BuyingAsset)
	appendOptionalString(fields[37].(*array.StringBuilder), row.BuyingAssetType)
	appendOptionalString(fields[38].(*array.StringBuilder), row.BuyingAssetCode)
	appendOptionalString(fields[39].(*array.StringBuilder), row.BuyingAssetIssuer)
	appendOptionalString(fields[40].(*array.StringBuilder), row.SellingAsset)
	appendOptionalString(fields[41].(*array.StringBuilder), row.SellingAssetType)
	appendOptionalString(fields[42].(*array.StringBuilder), row.SellingAssetCode)
	appendOptionalString(fields[43].(*array.StringBuilder), row.SellingAssetIssuer)
	appendOptionalString(fields[44].(*array.StringBuilder), row.SorobanOperation)
	appendOptionalString(fields[45].(*array.StringBuilder), row.SorobanFunction)
	appendOptionalString(fields[46].(*array.StringBuilder), row.SorobanContractID)
	appendOptionalBool(fields[47].(*array.BooleanBuilder), row.SorobanAuthRequired)
	appendOptionalInt64(fields[48].(*array.Int64Builder), row.BumpTo)
	if err := appendOptionalIntAsInt32(fields[49].(*array.Int32Builder), row.SetFlags); err != nil {
		return fmt.Errorf("set_flags: %w", err)
	}
	if err := appendOptionalIntAsInt32(fields[50].(*array.Int32Builder), row.ClearFlags); err != nil {
		return fmt.Errorf("clear_flags: %w", err)
	}
	appendOptionalString(fields[51].(*array.StringBuilder), row.HomeDomain)
	if err := appendOptionalIntAsInt32(fields[52].(*array.Int32Builder), row.MasterWeight); err != nil {
		return fmt.Errorf("master_weight: %w", err)
	}
	if err := appendOptionalIntAsInt32(fields[53].(*array.Int32Builder), row.LowThreshold); err != nil {
		return fmt.Errorf("low_threshold: %w", err)
	}
	if err := appendOptionalIntAsInt32(fields[54].(*array.Int32Builder), row.MediumThreshold); err != nil {
		return fmt.Errorf("medium_threshold: %w", err)
	}
	if err := appendOptionalIntAsInt32(fields[55].(*array.Int32Builder), row.HighThreshold); err != nil {
		return fmt.Errorf("high_threshold: %w", err)
	}
	appendOptionalString(fields[56].(*array.StringBuilder), row.DataName)
	appendOptionalString(fields[57].(*array.StringBuilder), row.DataValue)
	appendOptionalString(fields[58].(*array.StringBuilder), row.EraID)
	fields[59].(*array.StringBuilder).Append(contracts.ExtractionVersion)
	if err := appendIntAsInt32(fields[60].(*array.Int32Builder), row.TransactionIndex); err != nil {
		return fmt.Errorf("transaction_index: %w", err)
	}
	appendOptionalString(fields[61].(*array.StringBuilder), row.SorobanArgumentsJSON)
	appendOptionalString(fields[62].(*array.StringBuilder), row.ContractCallsJSON)
	if err := appendStringSliceJSON(fields[63].(*array.StringBuilder), row.ContractsInvolved); err != nil {
		return fmt.Errorf("contracts_involved: %w", err)
	}
	if err := appendOptionalIntAsInt32(fields[64].(*array.Int32Builder), row.MaxCallDepth); err != nil {
		return fmt.Errorf("max_call_depth: %w", err)
	}
	fields[65].(*array.Int64Builder).Append(int64(row.TransactionID))
	fields[66].(*array.Int64Builder).Append(int64(row.OperationID))
	fields[67].AppendNull()
	fields[68].AppendNull()
	return nil
}

var effectsBuilderLayout = mustTypedLayout("effects_row_v1")

type EffectsBuilder struct{ *extractRecordBuilder }

func NewEffectsBuilder(allocator memory.Allocator, reserve int) *EffectsBuilder {
	return &EffectsBuilder{extractRecordBuilder: newExtractRecordBuilder(effectsBuilderLayout.Schema, allocator, reserve)}
}

func (builder *EffectsBuilder) Schema() *arrow.Schema { return effectsBuilderLayout.Schema }

func (builder *EffectsBuilder) Append(row extract.EffectData) error {
	if builder == nil || builder.record == nil {
		return fmt.Errorf("typed extract builder is closed")
	}
	fields := builder.record.Fields()
	fields[0].(*array.Int64Builder).Append(int64(row.LedgerSequence))
	fields[1].(*array.StringBuilder).Append(row.TransactionHash)
	if err := appendIntAsInt32(fields[2].(*array.Int32Builder), row.OperationIndex); err != nil {
		return fmt.Errorf("operation_index: %w", err)
	}
	if err := appendIntAsInt32(fields[3].(*array.Int32Builder), row.EffectIndex); err != nil {
		return fmt.Errorf("effect_index: %w", err)
	}
	if err := appendIntAsInt32(fields[4].(*array.Int32Builder), row.EffectType); err != nil {
		return fmt.Errorf("effect_type: %w", err)
	}
	fields[5].(*array.StringBuilder).Append(row.EffectTypeString)
	appendOptionalString(fields[6].(*array.StringBuilder), row.AccountID)
	appendOptionalString(fields[7].(*array.StringBuilder), row.Amount)
	appendOptionalString(fields[8].(*array.StringBuilder), row.AssetCode)
	appendOptionalString(fields[9].(*array.StringBuilder), row.AssetIssuer)
	appendOptionalString(fields[10].(*array.StringBuilder), row.AssetType)
	appendOptionalString(fields[11].(*array.StringBuilder), row.TrustlineLimit)
	appendOptionalBool(fields[12].(*array.BooleanBuilder), row.AuthorizeFlag)
	appendOptionalBool(fields[13].(*array.BooleanBuilder), row.ClawbackFlag)
	appendOptionalString(fields[14].(*array.StringBuilder), row.SignerAccount)
	if err := appendOptionalIntAsInt32(fields[15].(*array.Int32Builder), row.SignerWeight); err != nil {
		return fmt.Errorf("signer_weight: %w", err)
	}
	appendOptionalInt64(fields[16].(*array.Int64Builder), row.OfferID)
	appendOptionalString(fields[17].(*array.StringBuilder), row.SellerAccount)
	fields[18].(*array.TimestampBuilder).Append(arrow.Timestamp(row.CreatedAt.UnixMicro()))
	fields[19].(*array.Int64Builder).Append(int64(row.LedgerRange))
	appendOptionalString(fields[20].(*array.StringBuilder), row.EraID)
	fields[21].(*array.StringBuilder).Append(contracts.ExtractionVersion)
	appendOptionalString(fields[22].(*array.StringBuilder), row.DetailsJSON)
	appendOptionalInt64(fields[23].(*array.Int64Builder), row.OperationID)
	return nil
}

var tokenTransfersBuilderLayout = mustTypedLayout("token_transfers_stream_v1")

type TokenTransfersBuilder struct{ *extractRecordBuilder }

func NewTokenTransfersBuilder(allocator memory.Allocator, reserve int) *TokenTransfersBuilder {
	return &TokenTransfersBuilder{extractRecordBuilder: newExtractRecordBuilder(tokenTransfersBuilderLayout.Schema, allocator, reserve)}
}

func (builder *TokenTransfersBuilder) Schema() *arrow.Schema {
	return tokenTransfersBuilderLayout.Schema
}

func (builder *TokenTransfersBuilder) Append(row extract.TokenTransferData) error {
	if builder == nil || builder.record == nil {
		return fmt.Errorf("typed extract builder is closed")
	}
	fields := builder.record.Fields()
	if err := appendUint32AsInt32(fields[0].(*array.Int32Builder), row.LedgerSequence); err != nil {
		return fmt.Errorf("ledger_sequence: %w", err)
	}
	fields[1].(*array.StringBuilder).Append(row.TransactionHash)
	fields[2].(*array.Int64Builder).Append(int64(row.TransactionID))
	appendOptionalInt64(fields[3].(*array.Int64Builder), row.OperationID)
	appendOptionalInt32(fields[4].(*array.Int32Builder), row.OperationIndex)
	fields[5].(*array.StringBuilder).Append(row.EventType)
	appendOptionalString(fields[6].(*array.StringBuilder), row.From)
	appendOptionalString(fields[7].(*array.StringBuilder), row.To)
	fields[8].(*array.StringBuilder).Append(row.Asset)
	fields[9].(*array.StringBuilder).Append(row.AssetType)
	appendOptionalString(fields[10].(*array.StringBuilder), row.AssetCode)
	appendOptionalString(fields[11].(*array.StringBuilder), row.AssetIssuer)
	fields[12].(*array.Float64Builder).Append(row.Amount)
	fields[13].(*array.StringBuilder).Append(row.AmountRaw)
	fields[14].(*array.StringBuilder).Append(row.ContractID)
	fields[15].(*array.TimestampBuilder).Append(arrow.Timestamp(row.ClosedAt.UnixMicro()))
	fields[16].(*array.TimestampBuilder).Append(arrow.Timestamp(row.CreatedAt.UnixMicro()))
	if err := appendUint32AsInt32(fields[17].(*array.Int32Builder), row.LedgerRange); err != nil {
		return fmt.Errorf("ledger_range: %w", err)
	}
	appendOptionalString(fields[18].(*array.StringBuilder), row.EraID)
	fields[19].(*array.StringBuilder).Append(contracts.ExtractionVersion)
	return nil
}
