package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"strings"
	"unicode"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/withObsrvr/obsrvr-stellar-components/pkg/bronze"
	bronzeColumnar "github.com/withObsrvr/obsrvr-stellar-components/pkg/bronze/columnar"
	"github.com/withObsrvr/obsrvr-stellar-components/pkg/contracts"
)

type table struct {
	name        string
	typeName    string
	builderName string
	rawOverride map[string]bool
}

var hotTables = []table{
	{
		name: "transactions_row_v2", typeName: "TransactionData", builderName: "TransactionsBuilder",
		rawOverride: map[string]bool{"tx_envelope": true, "tx_result": true, "tx_meta": true},
	},
	{name: "operations_row_v2", typeName: "OperationData", builderName: "OperationsBuilder"},
	{name: "effects_row_v1", typeName: "EffectData", builderName: "EffectsBuilder"},
	{name: "token_transfers_stream_v1", typeName: "TokenTransferData", builderName: "TokenTransfersBuilder"},
}

func main() {
	var output bytes.Buffer
	output.WriteString("// Code generated by go generate ./pkg/bronze/columnar; DO NOT EDIT.\n\n")
	output.WriteString("package columnar\n\n")
	output.WriteString("import (\n")
	output.WriteString("\t\"fmt\"\n\n")
	output.WriteString("\t\"github.com/apache/arrow-go/v18/arrow\"\n")
	output.WriteString("\t\"github.com/apache/arrow-go/v18/arrow/array\"\n")
	output.WriteString("\t\"github.com/apache/arrow-go/v18/arrow/memory\"\n")
	output.WriteString("\t\"github.com/withObsrvr/obsrvr-stellar-components/pkg/contracts\"\n")
	output.WriteString("\textract \"github.com/withObsrvr/stellar-extract\"\n")
	output.WriteString(")\n\n")

	for _, hot := range hotTables {
		if err := generateTable(&output, hot); err != nil {
			panic(err)
		}
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		panic(fmt.Errorf("format generated builders: %w\n%s", err, output.String()))
	}
	if err := os.WriteFile("hot_tables_gen.go", formatted, 0o644); err != nil {
		panic(err)
	}
}

func generateTable(output *bytes.Buffer, hot table) error {
	spec, ok := bronze.TypedTableSpecs[hot.name]
	if !ok {
		return fmt.Errorf("typed table %s is not registered", hot.name)
	}
	layout, err := bronzeColumnar.LayoutFor(spec)
	if err != nil {
		return err
	}
	fmt.Fprintf(output, "var %sLayout = mustTypedLayout(%q)\n\n", lowerFirst(hot.builderName), hot.name)
	fmt.Fprintf(output, "type %s struct { *extractRecordBuilder }\n\n", hot.builderName)
	fmt.Fprintf(output, "func New%s(allocator memory.Allocator, reserve int) *%s {\n", hot.builderName, hot.builderName)
	fmt.Fprintf(output, "\treturn &%s{extractRecordBuilder: newExtractRecordBuilder(%sLayout.Schema, allocator, reserve)}\n", hot.builderName, lowerFirst(hot.builderName))
	output.WriteString("}\n\n")
	fmt.Fprintf(output, "func (builder *%s) Schema() *arrow.Schema { return %sLayout.Schema }\n\n", hot.builderName, lowerFirst(hot.builderName))
	fmt.Fprintf(output, "func (builder *%s) Append(row extract.%s", hot.builderName, hot.typeName)
	if len(hot.rawOverride) > 0 {
		output.WriteString(", rawOverrides map[string]any")
	}
	output.WriteString(") error {\n")
	output.WriteString("\tif builder == nil || builder.record == nil { return fmt.Errorf(\"typed extract builder is closed\") }\n")
	output.WriteString("\tfields := builder.record.Fields()\n")
	for index, column := range spec.Columns {
		if err := generateColumn(output, hot, spec, layout, index, column); err != nil {
			return err
		}
	}
	output.WriteString("\treturn nil\n")
	output.WriteString("}\n\n")
	return nil
}

func generateColumn(output *bytes.Buffer, hot table, spec bronze.TypedTableSpec, layout bronzeColumnar.TypedTableLayout, index int, column string) error {
	field := layout.Schema.Field(index)
	target := fmt.Sprintf("fields[%d]", index)
	if defaultValue, ok := spec.ColumnDefaults[column]; ok {
		if field.Type.ID() != arrow.STRING {
			return fmt.Errorf("unsupported non-string default %s.%s", hot.name, column)
		}
		if column != "version_label" || defaultValue != contracts.ExtractionVersion {
			return fmt.Errorf("unsupported default %s.%s=%v", hot.name, column, defaultValue)
		}
		fmt.Fprintf(output, "\t%s.(*array.StringBuilder).Append(contracts.ExtractionVersion)\n", target)
		return nil
	}
	fieldName := exportedName(column)
	if override, ok := spec.ColumnOverrides[column]; ok {
		fieldName = override
	}
	rowField, ok := spec.RowType.FieldByName(fieldName)
	if !ok {
		if _, fallback := spec.ColumnJSONFallbacks[column]; !fallback {
			return fmt.Errorf("%s.%s has no field %s or fallback", hot.name, column, fieldName)
		}
		if hot.rawOverride[column] {
			if field.Type.ID() != arrow.STRING {
				return fmt.Errorf("raw override %s.%s is not string", hot.name, column)
			}
			fmt.Fprintf(output, "\tif err := appendRawTransactionString(%s.(*array.StringBuilder), rawOverrides, %q); err != nil { return fmt.Errorf(%q, err) }\n", target, column, column+": %w")
		} else {
			fmt.Fprintf(output, "\t%s.AppendNull()\n", target)
		}
		return nil
	}
	return generateFieldAppend(output, target, "row."+fieldName, column, field.Type.ID(), rowField.Type)
}

func generateFieldAppend(output *bytes.Buffer, target, value, column string, arrowType arrow.Type, goType reflect.Type) error {
	isPointer := goType.Kind() == reflect.Pointer
	baseType := goType
	if isPointer {
		baseType = goType.Elem()
	}
	switch arrowType {
	case arrow.STRING:
		switch {
		case isPointer && baseType.Kind() == reflect.String:
			fmt.Fprintf(output, "\tappendOptionalString(%s.(*array.StringBuilder), %s)\n", target, value)
		case !isPointer && baseType.Kind() == reflect.String:
			fmt.Fprintf(output, "\t%s.(*array.StringBuilder).Append(%s)\n", target, value)
		case !isPointer && baseType.Kind() == reflect.Slice && baseType.Elem().Kind() == reflect.String:
			fmt.Fprintf(output, "\tif err := appendStringSliceJSON(%s.(*array.StringBuilder), %s); err != nil { return fmt.Errorf(%q, err) }\n", target, value, column+": %w")
		default:
			return fmt.Errorf("unsupported VARCHAR field %s %s", column, goType)
		}
	case arrow.INT64:
		switch {
		case isPointer && baseType.Kind() == reflect.Int64:
			fmt.Fprintf(output, "\tappendOptionalInt64(%s.(*array.Int64Builder), %s)\n", target, value)
		case !isPointer && isSignedInteger(baseType.Kind()):
			fmt.Fprintf(output, "\t%s.(*array.Int64Builder).Append(int64(%s))\n", target, value)
		case !isPointer && isUnsignedInteger(baseType.Kind()) && baseType.Bits() <= 32:
			fmt.Fprintf(output, "\t%s.(*array.Int64Builder).Append(int64(%s))\n", target, value)
		default:
			return fmt.Errorf("unsupported BIGINT field %s %s", column, goType)
		}
	case arrow.INT32:
		switch {
		case isPointer && baseType.Kind() == reflect.Int32:
			fmt.Fprintf(output, "\tappendOptionalInt32(%s.(*array.Int32Builder), %s)\n", target, value)
		case isPointer && baseType.Kind() == reflect.Int:
			fmt.Fprintf(output, "\tif err := appendOptionalIntAsInt32(%s.(*array.Int32Builder), %s); err != nil { return fmt.Errorf(%q, err) }\n", target, value, column+": %w")
		case !isPointer && baseType.Kind() == reflect.Int32:
			fmt.Fprintf(output, "\t%s.(*array.Int32Builder).Append(%s)\n", target, value)
		case !isPointer && baseType.Kind() == reflect.Int:
			fmt.Fprintf(output, "\tif err := appendIntAsInt32(%s.(*array.Int32Builder), %s); err != nil { return fmt.Errorf(%q, err) }\n", target, value, column+": %w")
		case !isPointer && baseType.Kind() == reflect.Uint32:
			fmt.Fprintf(output, "\tif err := appendUint32AsInt32(%s.(*array.Int32Builder), %s); err != nil { return fmt.Errorf(%q, err) }\n", target, value, column+": %w")
		default:
			return fmt.Errorf("unsupported INTEGER field %s %s", column, goType)
		}
	case arrow.FLOAT64:
		if isPointer || baseType.Kind() != reflect.Float64 {
			return fmt.Errorf("unsupported DOUBLE field %s %s", column, goType)
		}
		fmt.Fprintf(output, "\t%s.(*array.Float64Builder).Append(%s)\n", target, value)
	case arrow.BOOL:
		if isPointer && baseType.Kind() == reflect.Bool {
			fmt.Fprintf(output, "\tappendOptionalBool(%s.(*array.BooleanBuilder), %s)\n", target, value)
		} else if !isPointer && baseType.Kind() == reflect.Bool {
			fmt.Fprintf(output, "\t%s.(*array.BooleanBuilder).Append(%s)\n", target, value)
		} else {
			return fmt.Errorf("unsupported BOOLEAN field %s %s", column, goType)
		}
	case arrow.TIMESTAMP:
		if isPointer || goType.String() != "time.Time" {
			return fmt.Errorf("unsupported TIMESTAMP field %s %s", column, goType)
		}
		fmt.Fprintf(output, "\t%s.(*array.TimestampBuilder).Append(arrow.Timestamp(%s.UnixMicro()))\n", target, value)
	default:
		return fmt.Errorf("unsupported Arrow type %s for %s", arrowType, column)
	}
	return nil
}

func isSignedInteger(kind reflect.Kind) bool {
	return kind >= reflect.Int && kind <= reflect.Int64
}

func isUnsignedInteger(kind reflect.Kind) bool {
	return kind >= reflect.Uint && kind <= reflect.Uint64
}

func exportedName(value string) string {
	parts := strings.Split(strings.Trim(value, `"`), "_")
	var result strings.Builder
	for _, part := range parts {
		switch strings.ToLower(part) {
		case "":
			continue
		case "id":
			result.WriteString("ID")
		case "xdr":
			result.WriteString("XDR")
		case "ttl":
			result.WriteString("TTL")
		case "tx":
			result.WriteString("Tx")
		case "json":
			result.WriteString("JSON")
		default:
			result.WriteRune(unicode.ToUpper(rune(part[0])))
			result.WriteString(part[1:])
		}
	}
	return result.String()
}

func lowerFirst(value string) string {
	if value == "" {
		return value
	}
	return strings.ToLower(value[:1]) + value[1:]
}
