apiVersion: v1
kind: Namespace
metadata:
  name: obsrvr-stellar
  labels:
    name: obsrvr-stellar
    environment: production
    project: obsrvr-components
    version: "1.0.0"
  annotations:
    obsrvr.com/description: "Production namespace for Obsrvr Stellar components"
    obsrvr.com/team: "platform"
    obsrvr.com/monitoring: "enabled"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: obsrvr-stellar
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    requests.storage: 1Ti
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: obsrvr-stellar
spec:
  limits:
  - default:
      memory: "2Gi"
      cpu: "1"
    defaultRequest:
      memory: "512Mi"
      cpu: "200m"
    type: Container
  - max:
      memory: "16Gi"
      cpu: "8"
    min:
      memory: "100Mi"
      cpu: "100m"
    type: Container