apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttp-arrow-processor
  namespace: obsrvr-stellar
  labels:
    app: ttp-arrow-processor
    component: processor
    environment: production
    version: "1.0.0"
spec:
  replicas: 5  # Scale for processing load
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: ttp-arrow-processor
  template:
    metadata:
      labels:
        app: ttp-arrow-processor
        component: processor
        environment: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: ttp-arrow-processor
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: ttp-arrow-processor
        image: obsrvr/ttp-arrow-processor:1.0.0
        imagePullPolicy: Always
        ports:
        - name: flight
          containerPort: 8816
          protocol: TCP
        - name: health
          containerPort: 8088
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: CONFIG_FILE
          value: "/etc/config/config.yaml"
        - name: LOG_LEVEL
          value: "info"
        - name: SOURCE_ENDPOINT
          value: "stellar-arrow-source.obsrvr-stellar.svc.cluster.local:8815"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "4"
        livenessProbe:
          httpGet:
            path: /health/live
            port: health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: health
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/live
            port: health
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: tls-certs
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: tls-keys
          mountPath: /etc/ssl/private
          readOnly: true
        - name: compute-spill
          mountPath: /tmp/compute-spill
        - name: tmp
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: ttp-arrow-processor-config
      - name: tls-certs
        secret:
          secretName: ttp-processor-tls-certs
      - name: tls-keys
        secret:
          secretName: ttp-processor-tls-keys
          defaultMode: 0400
      - name: compute-spill
        emptyDir:
          sizeLimit: 5Gi
      - name: tmp
        emptyDir:
          sizeLimit: 2Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ttp-arrow-processor
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values:
                - compute-optimized
      tolerations:
      - key: "obsrvr.com/stellar-workload"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: ttp-arrow-processor
  namespace: obsrvr-stellar
  labels:
    app: ttp-arrow-processor
    component: processor
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - name: flight
    port: 8816
    targetPort: flight
    protocol: TCP
  - name: health
    port: 8088
    targetPort: health
    protocol: TCP
  selector:
    app: ttp-arrow-processor
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ttp-arrow-processor-hpa
  namespace: obsrvr-stellar
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ttp-arrow-processor
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ttp-arrow-processor
  namespace: obsrvr-stellar
  labels:
    app: ttp-arrow-processor
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ttp-processor-role